name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: pythonconference
          changelog-types: '[{"type":"feat","section":"New","hidden":false},{"type":"fix","section":"Changed and fixed","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
        if: ${{ steps.release.outputs.release_created }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
        if: ${{ steps.release.outputs.release_created }}

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CC08D4C8EF264A09887268BBA5875EE7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E226939A58AB47288BD880E719736D28 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_66C811B5213F45AD908B4A13F745ABB7 }}
        if: ${{ steps.release.outputs.release_created }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'pythoneersconference'
          slot-name: 'Production'
          package: ./build
        if: ${{ steps.release.outputs.release_created }}
